version: '3.8'

services:
  # Telegram бот
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyberkitty19-transkribator-bot
    env_file:
      - .env
    volumes:
      - ./videos:/app/videos
      - ./audio:/app/audio
      - ./transcriptions:/app/transcriptions
      - ./transkribator_modules/workers:/app/transkribator_modules/workers
    restart: unless-stopped
    depends_on:
      - pyro-worker
    networks:
      - cyberkitty19-transkribator-network

  # Pyrogram воркер для больших файлов
  pyro-worker:
    build:
      context: .
      dockerfile: Dockerfile.pyro
    container_name: cyberkitty19-transkribator-pyro-worker
    env_file:
      - .env
    volumes:
      - ./videos:/app/videos
      - ./audio:/app/audio
      - ./transcriptions:/app/transcriptions
      - ./transkribator_modules/workers:/app/transkribator_modules/workers
      - ./transkribator_modules/workers/pyro_worker.session:/app/transkribator_modules/workers/pyro_worker.session
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - cyberkitty19-transkribator-network

  # API сервер
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: cyberkitty19-transkribator-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./videos:/app/videos
      - ./audio:/app/audio
      - ./transcriptions:/app/transcriptions
    restart: unless-stopped
    networks:
      - cyberkitty19-transkribator-network

networks:
  cyberkitty19-transkribator-network:
    driver: bridge

volumes:
  videos:
  audio:
  transcriptions: 