version: '3.8'

services:
  # Telegram бот (отвечает на команды)
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyberkitty19-transkribator-bot
    env_file:
      - .env
    volumes:
      - ./transkribator_modules:/app/transkribator_modules
      - ./videos:/app/videos
      - ./audio:/app/audio
      - ./transcriptions:/app/transcriptions
      - ./data:/app/data
      - ./secrets/google-sa.json:/app/credentials/google-sa.json:ro
      - ./transkribator.db:/app/transkribator.db
      - telegram-bot-api-data:/var/lib/telegram-bot-api:ro
    restart: unless-stopped
    depends_on:
      - telegram-bot-api
    networks:
      - cyberkitty19-transkribator-network
    environment:
      - TELEGRAM_API_URL=http://telegram-bot-api:8081/bot
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/google-sa.json
    command: sh -c "sleep 15 && python -m transkribator_modules.main"

  # Локальный бот (работает с API сервером для больших файлов)
  local-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyberkitty19-transkribator-local-bot
    env_file:
      - .env
    volumes:
      - ./transkribator_modules:/app/transkribator_modules
      - ./videos:/app/videos
      - ./audio:/app/audio
      - ./transcriptions:/app/transcriptions
      - ./data:/app/data
      - ./secrets/google-sa.json:/app/credentials/google-sa.json:ro
      - ./transkribator.db:/app/transkribator.db
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - cyberkitty19-transkribator-network
    environment:
      - LOCAL_API_URL=http://api:8000
      - LOCAL_API_KEY=${LOCAL_API_KEY:-}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/google-sa.json
    command: sh -c "sleep 10 && python -m transkribator_modules.local_bot"

  # API сервер
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: cyberkitty19-transkribator-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./videos:/app/videos
      - ./audio:/app/audio
      - ./transcriptions:/app/transcriptions
      - ./transkribator.db:/app/transkribator.db
    restart: unless-stopped
    networks:
      - cyberkitty19-transkribator-network

  # Telegram Bot API сервер
  telegram-bot-api:
    image: transkribator-telegram-bot-api
    container_name: cyberkitty19-telegram-bot-api
    command: /entrypoint.sh telegram-bot-api --api-id=21532963 --api-hash=66e38ebc131425924c2680e6c8fb6c09 --local
    restart: unless-stopped
    networks:
      cyberkitty19-transkribator-network:
        aliases:
          - api.telegram.org
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
      - "8082:8082"

networks:
  cyberkitty19-transkribator-network:
    driver: bridge

volumes:
  videos:
  audio:
  transcriptions:
  telegram-bot-api-data: 