FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-cacher-ng && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 3142

CMD ["apt-cacher-ng", "-c", "/etc/apt-cacher-ng", "Foreground=1"]
